#ifndef A5_SPARSE_AND_TAIL_ATTENTION_AND_SCATTER_COPY_TILING_H
#define A5_SPARSE_AND_TAIL_ATTENTION_AND_SCATTER_COPY_TILING_H

#include "a5_sfa_shared/sparse_flash_attention_tiling.h"

namespace optiling {

BEGIN_TILING_DATA_DEF(A5SparseAndTailAttentionAndScatterCopyTilingData)
TILING_DATA_FIELD_DEF_STRUCT(SparseFlashAttentionBaseParamsMla, baseParams);
TILING_DATA_FIELD_DEF_STRUCT(SparseFlashAttentionSplitKVParamsMla, splitKVParams);
TILING_DATA_FIELD_DEF_STRUCT(SparseFlashAttentionSingleCoreParamsMla, singleCoreParams);
TILING_DATA_FIELD_DEF_STRUCT(SparseFlashAttentionSingleCoreTensorSizeMla, singleCoreTensorSize);
TILING_DATA_FIELD_DEF_STRUCT(SparseFlashAttentionInnerSplitParams, innerSplitParams);
TILING_DATA_FIELD_DEF(uint32_t, copyCap);
TILING_DATA_FIELD_DEF(uint32_t, dramMaxBlockNum);
END_TILING_DATA_DEF

REGISTER_TILING_DATA_CLASS(
    A5SparseAndTailAttentionAndScatterCopy,
    A5SparseAndTailAttentionAndScatterCopyTilingData)

} // namespace optiling

#endif

