#ifndef A5_SPARSE_TAIL_ATTENTION_C8_PML_PROBE_TEMPLATE_TILING_KEY_H
#define A5_SPARSE_TAIL_ATTENTION_C8_PML_PROBE_TEMPLATE_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"

#define QSFA_LAYOUT_BSND 0
#define QSFA_LAYOUT_TND 1
#define QSFA_LAYOUT_PA_BSND 2
#define ASCENDC_TPL_4_BW 4
#define C_TEMPLATE 0
#define V_TEMPLATE 1

ASCENDC_TPL_ARGS_DECL(A5SparseTailAttentionC8PmlProbe,
ASCENDC_TPL_BOOL_DECL(FLASH_DECODE, 0, 1),
ASCENDC_TPL_BOOL_DECL(PAGE_ATTENTION, 0, 1),
ASCENDC_TPL_UINT_DECL(LAYOUT_T, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
                      QSFA_LAYOUT_BSND, QSFA_LAYOUT_TND),
ASCENDC_TPL_UINT_DECL(KV_LAYOUT_T, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
                      QSFA_LAYOUT_BSND, QSFA_LAYOUT_TND, QSFA_LAYOUT_PA_BSND),
ASCENDC_TPL_UINT_DECL(TEMPLATE_MODE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
                      C_TEMPLATE, V_TEMPLATE),
ASCENDC_TPL_BOOL_DECL(IS_SPLIT_G, 0, 1),
ASCENDC_TPL_BOOL_DECL(PROBE_ENABLED, 0, 1),
);

#define A5_C8_PROBE_SELECTION(PA, Q_LAYOUT, KV_LAYOUT) \
    ASCENDC_TPL_ARGS_SEL( \
    ASCENDC_TPL_BOOL_SEL(FLASH_DECODE, 0), \
    ASCENDC_TPL_BOOL_SEL(PAGE_ATTENTION, PA), \
    ASCENDC_TPL_UINT_SEL(LAYOUT_T, ASCENDC_TPL_UI_LIST, Q_LAYOUT), \
    ASCENDC_TPL_UINT_SEL(KV_LAYOUT_T, ASCENDC_TPL_UI_LIST, KV_LAYOUT), \
    ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, V_TEMPLATE), \
    ASCENDC_TPL_BOOL_SEL(IS_SPLIT_G, 0, 1), \
    ASCENDC_TPL_BOOL_SEL(PROBE_ENABLED, 0, 1), \
    )

ASCENDC_TPL_SEL(
    A5_C8_PROBE_SELECTION(0, QSFA_LAYOUT_BSND, QSFA_LAYOUT_BSND),
    A5_C8_PROBE_SELECTION(0, QSFA_LAYOUT_TND, QSFA_LAYOUT_TND),
    A5_C8_PROBE_SELECTION(1, QSFA_LAYOUT_BSND, QSFA_LAYOUT_PA_BSND),
    A5_C8_PROBE_SELECTION(1, QSFA_LAYOUT_TND, QSFA_LAYOUT_PA_BSND),
);

#undef A5_C8_PROBE_SELECTION

#endif
