/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 */

#ifndef NANOVLLM_SPARSE_AND_TAIL_ATTENTION_MTP_TEMPLATE_TILING_KEY_H
#define NANOVLLM_SPARSE_AND_TAIL_ATTENTION_MTP_TEMPLATE_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"

#define SFA_MTP_LAYOUT_TND 1
#define SFA_MTP_LAYOUT_PA_BSND 2
#define SFA_MTP_TPL_4_BW 4
#define SFA_MTP_V_TEMPLATE 1
#define C_TEMPLATE 0
#define V_TEMPLATE 1

ASCENDC_TPL_ARGS_DECL(NanovllmSparseAndTailAttentionMtp,
ASCENDC_TPL_BOOL_DECL(FLASH_DECODE, 0, 1),
ASCENDC_TPL_UINT_DECL(LAYOUT_T, SFA_MTP_TPL_4_BW, ASCENDC_TPL_UI_LIST, SFA_MTP_LAYOUT_TND),
ASCENDC_TPL_UINT_DECL(KV_LAYOUT_T, SFA_MTP_TPL_4_BW, ASCENDC_TPL_UI_LIST, SFA_MTP_LAYOUT_PA_BSND),
ASCENDC_TPL_UINT_DECL(TEMPLATE_MODE, SFA_MTP_TPL_4_BW, ASCENDC_TPL_UI_LIST, SFA_MTP_V_TEMPLATE),
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
    ASCENDC_TPL_BOOL_SEL(FLASH_DECODE, 0),
    ASCENDC_TPL_UINT_SEL(LAYOUT_T, ASCENDC_TPL_UI_LIST, SFA_MTP_LAYOUT_TND),
    ASCENDC_TPL_UINT_SEL(KV_LAYOUT_T, ASCENDC_TPL_UI_LIST, SFA_MTP_LAYOUT_PA_BSND),
    ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, SFA_MTP_V_TEMPLATE),
    ),
);

#endif
