#ifndef A5_SPARSE_TAIL_ATTENTION_C8_STAGE2_TILING_H
#define A5_SPARSE_TAIL_ATTENTION_C8_STAGE2_TILING_H

#define A5_C8_STAGE2_TILING_ONLY
#include "a5_sparse_tail_attention_c8_state_tiling.h"

#endif
